name: Main

on:
  pull_request:
  push:
    branches:
    - main

env:
  GO_VERSION: ^1.22.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - run: go test -v ./...
